export const GENRES = [
    "Action",
    "Comedy",
    "Drama",
    "Sci-Fi",
    "Thriller",
    "Horror",
    "Romance",
    "Crime",
    "Documentary",
    "War",
    "Biography",
    "History",
    "Sport",
    "Family",
];